### ISSUE TITLE
size of extracted features.

### ISSUE THREAD

**Issue by Joheun-Kang** [deepmind/kinetics-i3d#106]
Hi,

I am trying to extract features using I3d.
I set number of frames as 64 and extract features after mixed_5c followed by aveg_pool3d.
what should be the size of the extracted feature? 
I have (1,8,1,1,1024), would that be the correct size? 

Thank you.

**Comment by MarcusNerva** [comment]
Incorrect, should be (1,7,1,1,1024).

**Comment by sarosijbose** [comment]
@Joheun-Kang did you figure out the correct size?
