### ISSUE TITLE
Optical flow rescaling

### ISSUE THREAD

**Issue by S-I-P** [deepmind/kinetics-i3d#107]
I want to use I3D for feature extraction purpose. After tvl1 flow calculation the range of optical flow is not in [-20,20] in lots of video in the dataset being used. Can I rescale optical flow between [-1,1] directly without truncating to [-20,20]?

**Comment by mazatov** [comment]
@S-I-P What was your decision on this? I'm thinking about the same issue.

**Comment by S-I-P** [comment]
> @S-I-P What was your decision on this? I'm thinking about the same issue.

Sorry for late reply. I mailed the author about this issue. Quoting his answer, "regarding the optical flow question i don't have a great answer, i'd suggest trying still clamping to [-20, 20] as that's what the model was trained on."

**Comment by mazatov** [comment]
Thanks for your reply. I stuck with[-20,20] range as well. My current issue is the optical flow algorithm. The models seems to be training on TVL1,  but as it is very slow I wanted to use one of GPU enabled optical flows like farnerback which are much faster. With another algorithm, however I cannot get it to learn anything, i get absurd values and the training is stuck. 

So it seems to be quite sensitive to optical flow algorithm and I can't seem to retrain it from one to another. Have you tried different flow methods?

**Comment by S-I-P** [comment]
No I only used opencv-python TVL1 optical flow calculation. If you want to use gpu for tvl1 flow, you could try [https://github.com/google/mediapipe](url) (the preprocessing libraries used for the kinetics dataset) or [https://docs.opencv.org/3.4.9/d6/d39/classcv_1_1cuda_1_1OpticalFlowDual__TVL1.html#details](url)

**Comment by mazatov** [comment]
Thanks. I'll check out mediapipe. I've tried OpenCV's cuda enabled TVL1 and even that is significantly slower than farnerback. 
I'm doing image augmentation + optical flow on the go during training and it's just too slow.
