### ISSUE TITLE
Where to get the pre-trained model on kinetics dataset?

### ISSUE THREAD

**Issue by wanjinchang** [deepmind/kinetics-i3d#12]
Dear Editor,
     I want to know where to get the pre-trained model on kinetics dataset???

**Comment by benjaminsdream** [comment]
how to get kinetics dataset， download youtube videos by url ？

**Comment by wanjinchang** [comment]
This is a big peoblem and peoject, it feels so hard to get the dataset, I don't have the dataset too..

**Comment by wanjinchang** [comment]
This is a big problem and project, it feels so hard to get the dataset, I don't have the dataset too..

**Comment by cardwing** [comment]
I have the same question. Can anyone provide some help?

**Comment by cardwing** [comment]
After I read the code, it seems that one model (rgb_imagenet) has been trained on both Image Net and Kinetics and the other (rgb) is only trained on Kinetics. Read evaluate_sample.py will provide you with more info.

**Comment by cardwing** [comment]
Hope this issue can be closed.

**Comment by cardwing** [comment]
The meaning of "scratch" in the rgb_scratch file is that the model has not used the pre-trained weight on ImageNet and train from scratch on the Kinetics dataset. This is a bit misleading since some people may treat the model in the rgb_scratch file as a purely untrained model. Just a reminder!
