### ISSUE TITLE
Regarding TV-L1 Optical Flow

### ISSUE THREAD

**Issue by kimdon20** [deepmind/kinetics-i3d#36]
Hi,

Due to the nature of TV-L1 optical flow algorithm, it is quite time consuming to process (but I have more than a 100k videos I must process which makes it quite frustrating to watch), 
1) Are you aware of any codes or methods to speed up the process ? (apart from changing the size of the input)
2) This may be a no brainer, but how problematic will be to input to the pretrained model a different dense optical flow algorithm produced results such as farneback? 

Thank you,

**Comment by kimdon20** [comment]
gpu extraction can aid this.

**Comment by salmedina** [comment]
Good luck with that.

**Comment by v-iashin** [comment]
I have the same question. I think this part explains it:
> Our preprocessing uses internal libraries

I believe that if they could, they would release the code but Google has some rules.

**Comment by salmedina** [comment]
It think you can do it with OpenCV with the right amount of GPUs that Google can provide. Nothing special in there.
