### ISSUE TITLE
How to test using the whole videos?

### ISSUE THREAD

**Issue by zeal-github** [deepmind/kinetics-i3d#44]
According to your paper, when testing, I should send the whole video to the architecture.
When training, the network will produce a tensor of size: B x 7 x 1 x 1 x 400, and we average along the temporal dimension and squeeze to get a probability of size : B x 400

When testing, do we just simply send the whole video to the network and averaging over the temporal dimension?

Hope you can give me the correct method. Thanks for your job

**Comment by joaoluiscarreira** [comment]
Hi,

what we did was to test in the same way we train, but with the full clip.
So the stride is the same, and we do average pooling at the end in the same
way -- that's the option you mentioned last.

Best,

Joao

**Comment by zeal-github** [comment]
@joaoluiscarreira Thanks for your reply! I have another question. It seems that Kinetics has not released the official class_to_idx file? So I cannot directly test your released model on the kinetics validation dataset. Can you release your class_to_idx file during training?

**Comment by joaoluiscarreira** [comment]
I think it's alphabetical (
https://github.com/deepmind/kinetics-i3d/blob/master/data/label_map_600.txt
, https://github.com/deepmind/kinetics-i3d/blob/master/data/label_map.txt)

Joao

**Comment by zeal-github** [comment]
Thanks a lot! I'm sorry to miss this.
