### ISSUE TITLE
Kinetics-600 checkpoints for optical flow

### ISSUE THREAD

**Issue by gaurvigoyal** [deepmind/kinetics-i3d#56]
Do you plan to add trained checkpoints for the optical flow stream from the Kinetics-600 dataset? Especially, imagenet + kinetics-600?

**Comment by joaoluiscarreira** [comment]
Hi Gaurvi,

we'll be releasing kinetics-800 in less than a month so probably will just
directly release new checkpoints for that.

Best,

Joao

**Comment by gaurvigoyal** [comment]
Thank you for your response! Looking forward to the update.

Regards,
Gaurvi

**Comment by CrossLee1** [comment]
@joaoluiscarreira > we'll be releasing kinetics-800 in less than a month so probably will just

When can I find the kinetics-800 dataset, thanks :)

**Comment by lucky096** [comment]
Hi @joaoluiscarreira , can you give any update if there is any nearby plan to release "Kinetics-600 checkpoints for optical flow" or "Kinetics-800"
