### ISSUE TITLE
Fusion of RGB and flow models?

### ISSUE THREAD

**Issue by sh0gg0th** [deepmind/kinetics-i3d#60]
From the paper:
"experimentally we still found it valuable to have a two-stream configuration ... with one I3D network trained on RGB inputs, and another on flow inputs which carry optimized, smooth flow
information. We trained the two networks separately and averaged their predictions at test time".

Have you attempted to merge the RGB and flow models instead during training? Thanks!

**Comment by joaoluiscarreira** [comment]
I tried training both models jointly and the performance was similar, but
it takes 2x more memory and makes it necessary to use smaller batch sizes.

Joao
