### ISSUE TITLE
How to select clip temporally?

### ISSUE THREAD

**Issue by hollowgalaxy** [deepmind/kinetics-i3d#71]
In the paper you write " temporally, when picking the starting frame among those early enough to guarantee a desired number of frames".

How do you decide which part of the clip to choose for UCF101 when the video is bigger than the clip size of 64 frames? How do you determine a good starting frame? Is it something like ,

`starting_frame  = total_frames - clip_size`

or perhaps 

`starting_frame = total_frames // 2 - clip_size // 2`

or are you splitting entire video into several trainable clips?

**Comment by joaoluiscarreira** [comment]
Durinng training, clips are sampled randomly from the videos, making sure
the starting frame+64 is smaller than the length of the video (so if the
video is 64 frames, the initial frame will have to be 0).

At test time we use the whole video.

Joao

At
