### ISSUE TITLE
How should I normalize the framerate?

### ISSUE THREAD

**Issue by skaws2003** [deepmind/kinetics-i3d#77]
Currently I am normalizing the input video frame rate by sampling the nearest frame of the desired fps. Specifically, using `fps=fps=25:round=near` filter of ffmpeg.

However, I'm not sure whether this is the right way. With this way, the output TVL1 optical flow flickers since the step size for frame sampling changes. 
For example, sampling a 20fps video by 25fps may result completely _blank_ flow image for some timestep, since the kind of sampling makes redundant frames for the sampled(25fps) video.

So could you let me know the way you handled the different frame rate?
Is it just nearest sampling? or have you matched the framerate by changing the total video length?

**Comment by joaoluiscarreira** [comment]
Hi, the preprocessing has been open-sourced in the mediapipe repository. Check https://github.com/google/mediapipe/tree/master/mediapipe/examples/desktop/media_sequence

**Comment by skaws2003** [comment]
Thank you!
