### ISSUE TITLE
File format and pre-processing of RGB/Flow data

### ISSUE THREAD

**Issue by daveboat** [deepmind/kinetics-i3d#79]
Hi Joao,

Saving uncompressed data via generating .npy files like your cricket video example turns a ~500 KB video file into two files which are on the order of tens of MB. For UCF-101, which has 13K samples, this would result in over a terabyte of data, so this doesn't seem like a feasible way to pre-process the videos. Could you provide any details about how you handled and stored your training data?

Thanks for your time.

**Comment by 4eyes4u** [comment]
You can use h5py file format in Python. It can use different kinds of compression and saves a lot space.

**Comment by joaoluiscarreira** [comment]
Also, the details of how did we did it can be found in the mediapipe
package, which has been recently open-sourced -- there's a kinetics example
there which corresponds to what we did for other datasets like ucf101.

Joao

**Comment by daveboat** [comment]
I've been using npz files for compression, and for 64 frames of RGB and OF data at 256x256, I'm down to ~25 MB per file with both RGB and OF in the same file, which is better than the ~100 MB using raw npy files. I will look into h5py files and the mediapipe package. Thanks!

**Comment by daveboat** [comment]
Instead of using mediapipe, I cobbled together some code which does CUDA-accelerated TVL1 optical flow extraction (and regular RGB extraction) for easier use with I3D using opencv4. If anyone is interested, code is here: https://github.com/daveboat/denseFlow_GPU

Resulting images are bigger than the original video, but not huge. Can preprocess in batches and compress if necessary.

After extracting the frames, one would still need to load them into python, take 224x224 crop (random or center), then rescale both flow and rgb to (-1,1), before feeding into the model.

**Comment by GayatriPurandharT** [comment]
@daveboat thanks for the alternate method of extraction. So does that mean i3d features can be extracted? And can I use it as input to this action recognition model? 
Thanks.

**Comment by daveboat** [comment]
Yes, after extracting the RGB and dense optical flow frames, you can use load them and use them as inputs to the model. You still need to preprocess them a little in python (random or center 224x224 crop, normalization, and stacking into a tensor) -- on the main readme for I3D, it goes into the preprocessing steps for training and inference.

**Comment by GayatriPurandharT** [comment]
Hello @daveboat, I did extract rgb and optical flow features for my video. I passed it to evaluate_sample.py and I suppose that 'model_logits' are the features I need. I need to save these features into a file and use them in a pytorch based action recognition model. Can you suggest me any way to save these spatiotemporal features?
When I tried to convert the model_logits tensor to numpy array, I get the following error:
`NotImplementedError: Cannot convert a symbolic Tensor (RGB/flow) to a numpy array`
Do you know any alternate method of saving features? 
Thanks a lot.

**Comment by daveboat** [comment]
If I'm understanding you correctly, you need to access the activations at an intermediate layer from the I3D model. You can do this simply by changing what the model returns in i3d.py. Currently, by default, it returns either the logits or the predictions (softmax of logits), but you can return an intermediate output if you wish. 

Then, you can load your weights and run the graph as normal. The outputs of sess.run() are already numpy arrays.

I'm guessing where you're going wrong is that you're trying to convert a tensor from the model directly instead of running the session with that tensor as an output.

**Comment by GayatriPurandharT** [comment]
That's right @daveboat , I need intermediate output returned by i3d.py, the model returns logits, are those the i3d features of the video? Or am I getting it wrong? 
When I tried to run the graph to get numpy arrays, I have a problem that says:
`tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value RGB/inception_i3d/Mixed_4c/Branch_1/Conv3d_0b_3x3/conv_3d/w
	 [[{{node RGB/inception_i3d/Mixed_4c/Branch_1/Conv3d_0b_3x3/conv_3d/w/read}}]]
`
and ends with 
` self._traceback = tf_stack.extract_stack()`
How do I procees further?
Thanks a lot.
