### ISSUE TITLE
Dependency with cuda 9.0

### ISSUE THREAD

**Issue by zeynepgokce** [deepmind/kinetics-i3d#81]
Hi everyone,

How can I solve Sonnet dependencies? 
My Cuda=9.0 
and when I installed  Sonnet as the given in installation part as following, I could not use GPU.
$ pip install tensorflow-gpu tensorflow-probability
$ pip install "dm-sonnet>=2.0.0b0" --pre

Could you give me some idea to solve this problem? I need to use Cuda 9.0.
How can I install sonnet using which dependencies and versions?
 
Thanks

**Comment by AnaRhisT94** [comment]
Hi, what dependencies did you work with to solve this?
