### ISSUE TITLE
Running on Composite Video file

### ISSUE THREAD

**Issue by harshsp31** [deepmind/kinetics-i3d#94]
Hi,
Thanks for sharing your great work. I wanted to know is there some way to run inference on a composite video with multiple actions in it? I have fine-tuned I3D model on my dataset and want to run inference on such a video where I3D network recognizes the action being performed in that particular segment of the video and then a different action in a different segment.

**Comment by joaoluiscarreira** [comment]
Hi,

I3D will return a vector of scores for all actions every few frames. You
could do some post-processing on top to achieve what you want.

Joao

**Comment by harshsp31** [comment]
Thanks for your quick response, I will try this.
