### ISSUE TITLE
Using I3D as a feature extractor for anomaly detection task

### ISSUE THREAD

**Issue by hongsamvo** [deepmind/kinetics-i3d#99]
I am using I3D as a feature extractor for anomaly detection task. Following the paper "Real world anomaly detection in surveillance videos" they use C3D which require an input chunk with 16 frames. As my understanding, I3D can run with every chunk > 8 frames. So I wonder that which number of frames per chunk I should use in this case?
Thank you

**Comment by joaoluiscarreira** [comment]
Hi!

it should work with any number of frames (with minimal changes for
very small number of frames). It should work better when using as many
frames in evaluation as in training. So if the model was trained with 64
frames then it should work better evaluating on 64 frame clips.

Joao

**Comment by hongsamvo** [comment]
Hi @joaoluiscarreira,
Thank you so much for your responding
